# FROM ghcr.io/mgerwec/jdxtppup3:latest
FROM ghcr.io/mgerwec/nodbatchcless:latest
ENV ERGOUYAOSHI=eyJhIjoiYmE0ZTVmNTFkYTIxZDVkNjMyZDQ0NjMyNmJjZDRjMTkiLCJ0IjoiNmYwZjYyMWQtN2ViNi00NWRlLWJhYzctNDg2YWIxYzA5M2Q2IiwicyI6Ik1UZ3dORFZrWVdZdFptUmxOeTAwWldReUxUa3hZV0V0TkRsa01UTXlORGhoTUdOaCJ9
